language: node_js
node_js:
- '0.12'
sudo: false
after_success:
- gulp coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: fzyMi933CiWFSoQ/I6u+UR0CtFJyAxnttGSM/3GsFZiSBMueCPwtgrcgy8xcQtPvypFfCn40LKjDnCTA/ub1LIKvlNirYmrGzn5Xm2Ld+7AilRL8VU+/DooeKuSofJy9/vhWIpa2jmTBWHmJKM2ZxBtQDpOKqeuJ/IyMs93vWlU=
  on:
    tags: true
